Allow multiple simulators to run, and picking up where you left off.
biosimulations/biosimulations-runutils pull request #7
Opened 2024-09-23 20:45 UTC by luciansmith

2025-01-18 23:19 UTC, jcschaff requested changes
Lucian, sorry for the large number of comments, please take a look.  If you address them, then consider this approved.

2025-01-18 23:19 UTC, jcschaff commented on biosimulations_runutils/biosim_pipeline/main.py
> +            if run.status.lower()!="failed":
need to check for run.status being null, perhaps:


`if run.status is None:`
`    raise ValueError(f"Run {run} has no status")`

2025-01-18 23:19 UTC, jcschaff commented on biosimulations_runutils/biosim_pipeline/main.py
> +        simulator: Annotated[Simulator, typer.Option(help="simulator to run")] = None,
remove ` = None`, this is no longer an optional argument (None is not of type Simulator anyway).

2025-01-18 23:19 UTC, jcschaff commented on biosimulations_runutils/biosim_pipeline/hdf5_compare.py
>  def compare_arrays(arr1: np.ndarray, arr2: np.ndarray) -> bool:
return type changed, should now be:
`def compare_arrays(arr1: np.ndarray, arr2: np.ndarray) -> tuple[bool, float]:`

2025-01-18 23:19 UTC, jcschaff commented on biosimulations_runutils/biosim_pipeline/hdf5_compare.py
>  def compare_datasets(results1: dict[str, dict[str, np.ndarray]], results2: dict[str, dict[str, np.ndarray]]) -> bool:
return type is has changed, declared return type should be a tuple (as above):
`def compare_datasets(results1: dict[str, dict[str, np.ndarray]], results2: dict[str, dict[str, np.ndarray]]) -> tuple[bool, float]:`

2025-01-18 23:19 UTC, jcschaff commented on biosimulations_runutils/biosim_pipeline/hdf5_compare.py
> +    maxscore = 0
maxscore is a float, mypy doesn't like initializing an int and using it as a float.
`maxscore = 0.0`

2025-01-18 23:19 UTC, jcschaff commented on biosimulations_runutils/biosim_pipeline/main.py
> +        redo: Annotated[Union[str, None], typer.Option(help="Whether to re-run all files in directory ('all'), nothing that was already run before ('none'), or only new and previously-failed runs ('f
if None is not allowed shouldn't the type be str instead of Union[str, None], I think the typer.Option() can capture the optional nature of the argument.

2025-01-18 23:19 UTC, jcschaff commented on biosimulations_runutils/biosim_pipeline/main.py
> +    previous = set()
excuse the bike shedding - another typing request (this one MyPy did not complain about, but it made it more clear to me).
`previous: set[tuple[Simulator, str]] = set()`

2025-01-18 23:19 UTC, jcschaff commented on biosimulations_runutils/biosim_pipeline/main.py
> +                    print(f"project {source_omex.project_id} has been run before using {simulator}.")
shouldn't I be able to run it again with another simulator_version with the same simulator?  You decide on this one.  maybe `previous` should be type `set[tuple(Simulator, str, str)]` and include the version ...

2025-01-18 23:19 UTC, jcschaff commented on biosimulations_runutils/biosim_pipeline/main.py
>          if source_omex.project_id in projects:
`if source_omex.project_id in projects:` will never be true since `source_omex.project_id` is a `str` and `projects` is a `list[BiosimulationsProject]`

2025-01-18 23:19 UTC, jcschaff commented on biosimulations_runutils/biosim_pipeline/main.py
>          if source_omex.project_id in projects:
sorry this change is not from your PR, but please fix it while you are in there.

2025-01-18 23:19 UTC, jcschaff commented on biosimulations_runutils/biosim_pipeline/main.py
>          if source_omex.project_id in projects:
I found this with `mypy --strict .`

2025-01-18 23:19 UTC, jcschaff commented on biosimulations_runutils/biosim_pipeline/main.py
> +    ret = {}
what kind of dictionary? how about:
`def _convert_comparisons_to_dict(comparisons: list[SimulatorComparison]) -> dict[str, dict[tuple[Simulator, Simulator], bool]]:`
`    ret: dict[str, dict[tuple[Simulator, Simulator], bool]] = dict()`

2025-01-18 23:19 UTC, jcschaff commented on biosimulations_runutils/biosim_pipeline/hdf5_compare.py
> +        return close, score
what happens if you get a FloatingPointError above, it seems that score will not be initialized and you'll get a `UnboundLocalError` if you try to reference the score, maybe set score to a large value when you catch the FloatingPointError.

2025-01-22 21:51 UTC, luciansmith commented on biosimulations_runutils/biosim_pipeline/main.py
> +                    print(f"project {source_omex.project_id} has been run before using {simulator}.")
I don't have access to the current version of the simulator at this point.  It hasn't been an issue for me thus far because if I get a new simulator, I just delete the old runs wholesale.

2025-01-22 21:56 UTC, luciansmith commented on biosimulations_runutils/biosim_pipeline/hdf5_compare.py
> +        return close, score
Done!

2025-01-22 21:59 UTC, luciansmith commented on biosimulations_runutils/biosim_pipeline/main.py
> +            if run.status.lower()!="failed":
Done!

2025-01-22 22:02 UTC, luciansmith commented
@jcschaff 

OK, added the changes!  It's bizarre working in typed Python; it's like this added kludge that clearly was unwanted in the original design.  But hey!

If you want to run things through mypy once more to make sure the changes I made are accurate, that'd be great, but if you don't have time, don't worry about it.

2025-01-23 00:29 UTC, merged

2025-01-23 00:30 UTC, luciansmith commented
Can't figure out how to resolve the requested change, but hey.  Thanks, Jim!